services:
  transcription:
    image: thegreatcodeholio/icad_transcribe:1.0
    user: "icad_dispatch"
    env_file:
      - .env
    ports:
      - "9912:9912"
    volumes:
      - ./log:/app/log        # ensure host perms: chown -R 9911:9911 log var
      - ./var:/app/var
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
              # device_ids: ['0','3']  # optional: target specific GPUs
    restart: unless-stopped
